version: '3'
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/magixsupport
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    networks:
      - app-network

  magixsupport:
    build:
      context: ../
      dockerfile: Dockerfile
    image: klyent.co/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: magixsupport
      SERVICE_TAGS: dev
    working_dir: /var/www/magixsupport
    volumes:
      - ../:/var/www/magixsupport
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
